jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install -r requirements.txt
      - run: pytest -q           # unit tests
      - run: flake8 .            # style check
  retrain:
    needs: build-test
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python pipelines/retrain_model.py
      - uses: actions/upload-artifact@v4
        with: {name: knn_model, path: models/knn_model.pkl}
